version: "3.8"
services:
  api-catalago:
    env_file: .env

    build:
      dockerfile: "Dockerfile"
      context: ./api-catalogo/.

    image: api-catalogo

    container_name: api-catalogo

    ports:
      - $API_CATALOGO_PORT:$API_CATALOGO_PORT

    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.1-bionic
    env_file: .env
    container_name: mongo
    ports:
      - $MONGO_PORT:$MONGO_PORT

  api-recomendacao:
    env_file: .env
    build:
      dockerfile: "Dockerfile"
      context: ./api-recomendacao/.
    image: api-recomendacao
    container_name: api-recomendacao
    ports:
      - $API_RECOMENDACAO_PORT:$API_RECOMENDACAO_PORT

    depends_on:
      - api-catalago

  frontend-app:
    env_file: .env
    build:
      dockerfile: "Dockerfile"
      context: ./frontend/.
    image: frontend-app
    container_name: frontend-app
    ports:
      - $FRONTEND_PORT:$FRONTEND_PORT

    depends_on:
      - api-recomendacao
